/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type AttendanceResponseStatus = typeof AttendanceResponseStatus[keyof typeof AttendanceResponseStatus];


export const AttendanceResponseStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  JOINED_LATE: 'JOINED_LATE',
} as const;
