/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceResponseStatus } from './attendanceResponseStatus';

export interface AttendanceResponse {
  id: string;
  user_id: string;
  meeting_id: string;
  status: AttendanceResponseStatus;
  /** @nullable */
  joined_at?: string | null;
}
