/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { AuthResponseDataUser } from './authResponseDataUser';

export type AuthResponseData = {
  user: AuthResponseDataUser;
  access_token: string;
  refresh_token: string;
};
