/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type AuthResponseDataUserProfileStatus = typeof AuthResponseDataUserProfileStatus[keyof typeof AuthResponseDataUserProfileStatus];


export const AuthResponseDataUserProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
