/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type BatchDataResponseData = {
  id: string;
  batch_name: string;
  batch_code: string;
  description: string;
  image_url: string;
  total_classes: number;
  batch_start_date: string;
  batch_end_date: string;
  estimated_end_date: string;
  mentor_ids: string[];
  course_ids: string[];
  /** @nullable */
  current_course_id: string | null;
  completed_course_ids: string[];
  meeting_id: string;
  created_at: string;
};
