/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type BatchWithDetailsResponseStudentsItemRole = typeof BatchWithDetailsResponseStudentsItemRole[keyof typeof BatchWithDetailsResponseStudentsItemRole];


export const BatchWithDetailsResponseStudentsItemRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
