/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { CourseResponseWeeklyContentItem } from './courseResponseWeeklyContentItem';

export interface CourseResponse {
  id: string;
  name: string;
  description: string;
  lesson_ids: string[];
  time_allotted_in_weeks: number;
  weekly_content: CourseResponseWeeklyContentItem[];
  created_at: string;
  updated_at: string;
}
