/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCourseRequestModulesItem } from './createCourseRequestModulesItem';
import type { CreateCourseRequestStatus } from './createCourseRequestStatus';

export interface CreateCourseRequest {
  title: string;
  description: string;
  status?: CreateCourseRequestStatus;
  modules?: CreateCourseRequestModulesItem[];
}
