/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type CreateBatchRequestRequestChangeType = typeof CreateBatchRequestRequestChangeType[keyof typeof CreateBatchRequestRequestChangeType];


export const CreateBatchRequestRequestChangeType = {
  date: 'date',
  reschedule: 'reschedule',
  size: 'size',
} as const;
