/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCourseRequest {
  name: string;
  description: string;
  time_allotted_in_weeks: number;
}
