/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCourseRequestModulesItemLecturesItem } from './createCourseRequestModulesItemLecturesItem';

export type CreateCourseRequestModulesItem = {
  title: string;
  sequence_order?: number;
  lectures?: CreateCourseRequestModulesItemLecturesItem[];
};
