/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMeetingRequest {
  title: string;
  description: string;
  batch_id: string;
  scheduled_start_time: string;
  /** @exclusiveMinimum 0 */
  duration_minutes?: number;
}
