/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBatchRequestRequestChangeType } from './createBatchRequestRequestChangeType';

export interface CreateBatchRequestRequest {
  batch_code: string;
  change_type: CreateBatchRequestRequestChangeType;
  /** @nullable */
  proposed_value?: string | null;
  reason: string;
}
