/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminUsers200DataItemRole = typeof GetAdminUsers200DataItemRole[keyof typeof GetAdminUsers200DataItemRole];


export const GetAdminUsers200DataItemRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  MENTOR_EDITOR: 'MENTOR_EDITOR',
  ADMIN: 'ADMIN',
} as const;
