/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminUsers200DataItemProfileStatus } from './getAdminUsers200DataItemProfileStatus';
import type { GetAdminUsers200DataItemRole } from './getAdminUsers200DataItemRole';

export type GetAdminUsers200DataItem = {
  id: string;
  email: string;
  username: string;
  full_name: string;
  role: GetAdminUsers200DataItemRole;
  profile_status: GetAdminUsers200DataItemProfileStatus;
  skills: string[];
  /** @nullable */
  linkedin_url?: string | null;
  /** @nullable */
  github_url?: string | null;
  /** @nullable */
  x_url?: string | null;
  /** @nullable */
  zulip_username?: string | null;
  did_internship: boolean;
  /**
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  college_year?: number | null;
  batch_ids: string[];
  created_at: string;
};
