/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminCourses200DataItem } from './getAdminCourses200DataItem';

export type GetAdminCourses200 = {
  data: GetAdminCourses200DataItem[];
  message: string;
};
