/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetBatchId200DataStudentsItemRole = typeof GetBatchId200DataStudentsItemRole[keyof typeof GetBatchId200DataStudentsItemRole];


export const GetBatchId200DataStudentsItemRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
