/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetBatchIdMeetings200DataItem } from './getBatchIdMeetings200DataItem';

export type GetBatchIdMeetings200 = {
  data: GetBatchIdMeetings200DataItem[];
  message: string;
};
