/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetBatchIdMeetings200DataItemStatus = typeof GetBatchIdMeetings200DataItemStatus[keyof typeof GetBatchIdMeetings200DataItemStatus];


export const GetBatchIdMeetings200DataItemStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
