/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetBatchRequestsMy200DataItem } from './getBatchRequestsMy200DataItem';

export type GetBatchRequestsMy200 = {
  data: GetBatchRequestsMy200DataItem[];
  message: string;
};
