/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetBatchId200DataStudentsItemProfileStatus = typeof GetBatchId200DataStudentsItemProfileStatus[keyof typeof GetBatchId200DataStudentsItemProfileStatus];


export const GetBatchId200DataStudentsItemProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
