/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetBatch200DataItem } from './getBatch200DataItem';

export type GetBatch200 = {
  data: GetBatch200DataItem[];
  message: string;
};
