/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetBatchId200DataMeetingsItemStatus = typeof GetBatchId200DataMeetingsItemStatus[keyof typeof GetBatchId200DataMeetingsItemStatus];


export const GetBatchId200DataMeetingsItemStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
