/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetBatchIdMeetings200DataItemStatus } from './getBatchIdMeetings200DataItemStatus';

export type GetBatchIdMeetings200DataItem = {
  id: string;
  title: string;
  description: string;
  batch_id: string;
  scheduled_start_time: string;
  duration_minutes: number;
  status: GetBatchIdMeetings200DataItemStatus;
  /** @nullable */
  actual_start_time?: string | null;
  /** @nullable */
  actual_end_time?: string | null;
  created_at: string;
};
