/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeetingIdParticipants200DataItem } from './getMeetingIdParticipants200DataItem';

export type GetMeetingIdParticipants200 = {
  data: GetMeetingIdParticipants200DataItem[];
  message: string;
};
