/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeeting200DataItem } from './getMeeting200DataItem';

export type GetMeeting200 = {
  data: GetMeeting200DataItem[];
  message: string;
};
