/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetMeetingId200DataStatus = typeof GetMeetingId200DataStatus[keyof typeof GetMeetingId200DataStatus];


export const GetMeetingId200DataStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
