/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeetingIdAttendance200DataItemStatus } from './getMeetingIdAttendance200DataItemStatus';

export type GetMeetingIdAttendance200DataItem = {
  id: string;
  user_id: string;
  meeting_id: string;
  status: GetMeetingIdAttendance200DataItemStatus;
  /** @nullable */
  joined_at?: string | null;
};
