/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetMeetingIdParticipants200DataItemRole = typeof GetMeetingIdParticipants200DataItemRole[keyof typeof GetMeetingIdParticipants200DataItemRole];


export const GetMeetingIdParticipants200DataItemRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
