/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeetingId200Data } from './getMeetingId200Data';

export type GetMeetingId200 = {
  data: GetMeetingId200Data;
  message: string;
};
