/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetMeetingIdAttendance200DataItemStatus = typeof GetMeetingIdAttendance200DataItemStatus[keyof typeof GetMeetingIdAttendance200DataItemStatus];


export const GetMeetingIdAttendance200DataItemStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  PARTIALLY_PRESENT: 'PARTIALLY_PRESENT',
} as const;
