/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMeetingIdAttendance200DataItem } from './getMeetingIdAttendance200DataItem';

export type GetMeetingIdAttendance200 = {
  data: GetMeetingIdAttendance200DataItem[];
  message: string;
};
