/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetMeetingIdParticipants200DataItemProfileStatus = typeof GetMeetingIdParticipants200DataItemProfileStatus[keyof typeof GetMeetingIdParticipants200DataItemProfileStatus];


export const GetMeetingIdParticipants200DataItemProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
