/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200Data } from './getUser200Data';

export type GetUser200 = {
  data: GetUser200Data;
  message: string;
};
