/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserGithubLogin200Data } from './getUserGithubLogin200Data';

export type GetUserGithubLogin200 = {
  data: GetUserGithubLogin200Data;
  message: string;
};
