/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type GetUserGithubCallback200DataUserRole = typeof GetUserGithubCallback200DataUserRole[keyof typeof GetUserGithubCallback200DataUserRole];


export const GetUserGithubCallback200DataUserRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
