/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserGithubCallback200Data } from './getUserGithubCallback200Data';

export type GetUserGithubCallback200 = {
  data: GetUserGithubCallback200Data;
  message: string;
};
