/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { GithubAuthResponseDataUser } from './githubAuthResponseDataUser';

export type GithubAuthResponseData = {
  user: GithubAuthResponseDataUser;
  access_token: string;
  refresh_token: string;
  is_new_user: boolean;
};
