/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API collection for AKXR Backend - UniDrop service
 * OpenAPI spec version: 1.0.0
 */

export * from './getUserGithubCallbackParams';