/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUser200Data } from './patchUser200Data';

export type PatchUser200 = {
  data: PatchUser200Data;
  message: string;
};
