/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PatchMeetingIdAttendance200DataStatus } from './patchMeetingIdAttendance200DataStatus';

export type PatchMeetingIdAttendance200Data = {
  id: string;
  user_id: string;
  meeting_id: string;
  status: PatchMeetingIdAttendance200DataStatus;
  /** @nullable */
  joined_at?: string | null;
};
