/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PatchBatchId200Data } from './patchBatchId200Data';

export type PatchBatchId200 = {
  data: PatchBatchId200Data;
  message: string;
};
