/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PatchMeetingIdAttendanceBodyStatus } from './patchMeetingIdAttendanceBodyStatus';

export type PatchMeetingIdAttendanceBody = {
  user_id: string;
  status: PatchMeetingIdAttendanceBodyStatus;
};
