/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PatchMeetingIdAttendance200DataStatus = typeof PatchMeetingIdAttendance200DataStatus[keyof typeof PatchMeetingIdAttendance200DataStatus];


export const PatchMeetingIdAttendance200DataStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  JOINED_LATE: 'JOINED_LATE',
} as const;
