/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PatchUser200DataProfileStatus = typeof PatchUser200DataProfileStatus[keyof typeof PatchUser200DataProfileStatus];


export const PatchUser200DataProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
