/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostMeetingIdStart200Data } from './postMeetingIdStart200Data';

export type PostMeetingIdStart200 = {
  data: PostMeetingIdStart200Data;
  message: string;
};
