/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAuthSignin200DataUserProfileStatus = typeof PostUserAuthSignin200DataUserProfileStatus[keyof typeof PostUserAuthSignin200DataUserProfileStatus];


export const PostUserAuthSignin200DataUserProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
