/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostBatchRequests201Data = {
  id: string;
  batch_code: string;
  mentor_id: string;
  change_type: string;
  /** @nullable */
  proposed_value?: string | null;
  reason: string;
  status: string;
  created_at: string;
  updated_at: string;
};
