/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostMeeting201Data } from './postMeeting201Data';

export type PostMeeting201 = {
  data: PostMeeting201Data;
  message: string;
};
