/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostBatchRequestsBodyChangeType = typeof PostBatchRequestsBodyChangeType[keyof typeof PostBatchRequestsBodyChangeType];


export const PostBatchRequestsBodyChangeType = {
  date: 'date',
  reschedule: 'reschedule',
  size: 'size',
} as const;
