/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserAuthRefresh200Data } from './postUserAuthRefresh200Data';

export type PostUserAuthRefresh200 = {
  data: PostUserAuthRefresh200Data;
  message: string;
};
