/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostBatchRequests201Data } from './postBatchRequests201Data';

export type PostBatchRequests201 = {
  data: PostBatchRequests201Data;
  message: string;
};
