/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAuthSignup201DataUserRole = typeof PostUserAuthSignup201DataUserRole[keyof typeof PostUserAuthSignup201DataUserRole];


export const PostUserAuthSignup201DataUserRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  MENTOR_EDITOR: 'MENTOR_EDITOR',
  ADMIN: 'ADMIN',
} as const;
