/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserCompleteProfile200Data } from './postUserCompleteProfile200Data';

export type PostUserCompleteProfile200 = {
  data: PostUserCompleteProfile200Data;
  message: string;
};
