/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAuthSignup201DataUserProfileStatus = typeof PostUserAuthSignup201DataUserProfileStatus[keyof typeof PostUserAuthSignup201DataUserProfileStatus];


export const PostUserAuthSignup201DataUserProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
