/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostAdminUpgradeRole200DataRole } from './postAdminUpgradeRole200DataRole';

export type PostAdminUpgradeRole200Data = {
  id: string;
  username: string;
  email: string;
  role: PostAdminUpgradeRole200DataRole;
};
