/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostMeetingIdStart200DataStatus = typeof PostMeetingIdStart200DataStatus[keyof typeof PostMeetingIdStart200DataStatus];


export const PostMeetingIdStart200DataStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
