/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostAdminUpgradeRole200Data } from './postAdminUpgradeRole200Data';

export type PostAdminUpgradeRole200 = {
  data: PostAdminUpgradeRole200Data;
  message: string;
};
