/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserAuthSignin200DataUserRole = typeof PostUserAuthSignin200DataUserRole[keyof typeof PostUserAuthSignin200DataUserRole];


export const PostUserAuthSignin200DataUserRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
