/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserCompleteProfile200DataProfileStatus = typeof PostUserCompleteProfile200DataProfileStatus[keyof typeof PostUserCompleteProfile200DataProfileStatus];


export const PostUserCompleteProfile200DataProfileStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  PROFILE_CREATED: 'PROFILE_CREATED',
} as const;
