/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostUserCompleteProfile200DataRole = typeof PostUserCompleteProfile200DataRole[keyof typeof PostUserCompleteProfile200DataRole];


export const PostUserCompleteProfile200DataRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
