/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostAdminUpgradeRoleBodyNewRole = typeof PostAdminUpgradeRoleBodyNewRole[keyof typeof PostAdminUpgradeRoleBodyNewRole];


export const PostAdminUpgradeRoleBodyNewRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  MENTOR_EDITOR: 'MENTOR_EDITOR',
  ADMIN: 'ADMIN',
} as const;
