/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostMeetingIdEnd200Data } from './postMeetingIdEnd200Data';

export type PostMeetingIdEnd200 = {
  data: PostMeetingIdEnd200Data;
  message: string;
};
