/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostMeetingIdEnd200DataStatus = typeof PostMeetingIdEnd200DataStatus[keyof typeof PostMeetingIdEnd200DataStatus];


export const PostMeetingIdEnd200DataStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
