/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostAdminCoursesBodyStatus = typeof PostAdminCoursesBodyStatus[keyof typeof PostAdminCoursesBodyStatus];


export const PostAdminCoursesBodyStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
