/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserAuthSignup201DataUser } from './postUserAuthSignup201DataUser';

export type PostUserAuthSignup201Data = {
  user: PostUserAuthSignup201DataUser;
  access_token: string;
  refresh_token: string;
};
