/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostAdminUpgradeRole200DataRole = typeof PostAdminUpgradeRole200DataRole[keyof typeof PostAdminUpgradeRole200DataRole];


export const PostAdminUpgradeRole200DataRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
