/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostAdminCoursesBodyModulesItem } from './postAdminCoursesBodyModulesItem';
import type { PostAdminCoursesBodyStatus } from './postAdminCoursesBodyStatus';

export type PostAdminCoursesBody = {
  title: string;
  description: string;
  status?: PostAdminCoursesBodyStatus;
  modules?: PostAdminCoursesBodyModulesItem[];
};
