/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserAuthSignin200DataUser } from './postUserAuthSignin200DataUser';

export type PostUserAuthSignin200Data = {
  user: PostUserAuthSignin200DataUser;
  access_token: string;
  refresh_token: string;
};
