/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserAuthSignin200Data } from './postUserAuthSignin200Data';

export type PostUserAuthSignin200 = {
  data: PostUserAuthSignin200Data;
  message: string;
};
