/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type PostMeeting201DataStatus = typeof PostMeeting201DataStatus[keyof typeof PostMeeting201DataStatus];


export const PostMeeting201DataStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  CANCELLED: 'CANCELLED',
} as const;
