/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostBatchRequestsBodyChangeType } from './postBatchRequestsBodyChangeType';

export type PostBatchRequestsBody = {
  batch_code: string;
  change_type: PostBatchRequestsBodyChangeType;
  /** @nullable */
  proposed_value?: string | null;
  reason: string;
};
