/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { PostAdminCoursesBodyModulesItemLecturesItem } from './postAdminCoursesBodyModulesItemLecturesItem';

export type PostAdminCoursesBodyModulesItem = {
  title: string;
  sequence_order?: number;
  lectures?: PostAdminCoursesBodyModulesItemLecturesItem[];
};
