/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export interface SignInWithEmailRequest {
  email: string;
  /** @minLength 1 */
  password: string;
}
