/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpWithEmailRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 3
   * @maxLength 50
   * @pattern ^[a-zA-Z0-9_-]+$
   */
  username: string;
  /** @minLength 2 */
  full_name: string;
}
