/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateBatchRequest {
  /** @minimum 0 */
  total_classes?: number;
  batch_name?: string;
  mentor_ids?: string[];
  batch_start_date?: string;
  batch_end_date?: string;
  estimated_end_date?: string;
  /** @nullable */
  current_course_id?: string | null;
  course_ids?: string[];
  completed_course_ids?: string[];
  /** @maxLength 4 */
  batch_code?: string;
  description?: string;
  image_url?: string;
  meeting_id?: string;
}
