/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type UpdateAttendanceRequestStatus = typeof UpdateAttendanceRequestStatus[keyof typeof UpdateAttendanceRequestStatus];


export const UpdateAttendanceRequestStatus = {
  PRESENT: 'PRESENT',
  PARTIALLY_PRESENT: 'PARTIALLY_PRESENT',
  ABSENT: 'ABSENT',
} as const;
