/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */

export type UpgradeRoleResponseDataRole = typeof UpgradeRoleResponseDataRole[keyof typeof UpgradeRoleResponseDataRole];


export const UpgradeRoleResponseDataRole = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
  ADMIN: 'ADMIN',
} as const;
