/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { UpgradeRoleResponseDataRole } from './upgradeRoleResponseDataRole';

export type UpgradeRoleResponseData = {
  id: string;
  username: string;
  email: string;
  role: UpgradeRoleResponseDataRole;
};
