/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { UpgradeRoleResponseData } from './upgradeRoleResponseData';

export interface UpgradeRoleResponse {
  data: UpgradeRoleResponseData;
  message: string;
}
