/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AKXR Backend API
 * API documentation for AKXR Backend
 * OpenAPI spec version: 1.0.0
 */
import type { UpgradeRoleRequestNewRole } from './upgradeRoleRequestNewRole';

export interface UpgradeRoleRequest {
  user_id: string;
  new_role: UpgradeRoleRequestNewRole;
}
